name: movie_search
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_rating:
  cupertino_icons: ^0.1.2
  async_loader:
  flutter_youtube:
  cached_network_image:
  material_design_icons_flutter:
  flutter_facebook_login:
  google_sign_in:
  firebase_auth:
  firebase_core:
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
