name: movie_search
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_rating:
  cupertino_icons: ^0.1.2
  async_loader:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
